name         'camptocamp-openssl'
version      '0.1.0'
dependency   'puppetlabs/stdlib', '0.0.1'
source       'https://github.com/camptocamp/puppet-openssl'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp OpenSSL Module'
description  'OpenSSL Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-openssl'
